# Generated by Django 5.0 on 2024-01-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="pkid",
            field=models.BigAutoField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
