# Generated by Django 5.0 on 2024-01-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_profile_pkid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="pkid",
            field=models.BigIntegerField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
